[package]
name = "voluntary-servitude"
version = "1.0.0"
authors = ["Paulo Cabral Sanz <paulosanz@poli.ufrj.br>"]

[lib]
name = "voluntary_servitude"
crate_type = ["lib", "cdylib"]

[dependencies]
log = { version = "0.4", optional = true }
env_logger = { version = "0.5", optional = true }

[features]
default = []
logs = ["log", "env_logger"]
