[package]
name = "voluntary-servitude"
version = "1.0.4"
authors = ["Paulo Cabral Sanz <paulosanz@poli.ufrj.br>"]
description = "Thread-safe appendable list with lock-free iterator"
repository = "https://github.com/paulocsanz/voluntary-servitude"
license = "MIT"
readme = "README.md"
keywords = ["lock-free", "mutex", "iterator", "appendable", "list"]
categories = ["concurrency"]

[lib]
name = "voluntary_servitude"
crate_type = ["lib", "cdylib"]

[dependencies]
log = { version = "0.4", optional = true }
env_logger = { version = "0.5", optional = true }

[features]
default = []
logs = ["log", "env_logger"]
jemmaloc = []
